---
cog_bundle_version: 4
name: autoscaling
description: Interact with autoscaling in AWS
version: 0.0.12
docker:
  image: quay.io/honestbee/cog-autoscaling
  tag: 0.0.12
commands:
  group:
    description: Manages an autoscaling group
    executable: /usr/local/bin/cog-command
    documentation: |
      Manages an AWS autoscaling group
      autoscaling:group list
      autoscaling:group scale -n [autoscaling group name] -d [number of instances]
    options:
      name:
        type: string
        required: false
        short_flag: n
      desired:
        type: int
        required: false
        short_flag: d
    rules:
      - allow
